// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScreenEdge.Entity;

#nullable disable

namespace ScreenEdge.Entity.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817035928_AddFinnhubFundamentals")]
    partial class AddFinnhubFundamentals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ScreenEdge.Entity.Entities.DistinctStock", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Exchange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("MarketCap")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TotalTradingDays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("DistinctStocks");
                });

            modelBuilder.Entity("ScreenEdge.Entity.Entities.Screener", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("RecognizeDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("RecognizedPrice")
                        .HasColumnType("float");

                    b.Property<double>("Rsi")
                        .HasColumnType("float");

                    b.Property<double>("RsiMonthly")
                        .HasColumnType("float");

                    b.Property<double>("RsiWeekly")
                        .HasColumnType("float");

                    b.Property<string>("ScreenerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TimeFrame")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RecognizeDate");

                    b.HasIndex("ScreenerName");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "ScreenerName", "TimeFrame", "RecognizeDate")
                        .IsUnique();

                    b.ToTable("Screeners");
                });

            modelBuilder.Entity("ScreenEdge.Entity.Entities.StockFundamental", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("DistinctStockId")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("DividendYield")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FiftyTwoWeekHigh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FiftyTwoWeekLow")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("PbRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("PeRatio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistinctStockId")
                        .IsUnique();

                    b.ToTable("StockFundamentals");
                });

            modelBuilder.Entity("ScreenEdge.Entity.Entities.TickerHistory", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("Close")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("High")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Low")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Open")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Volume")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Symbol");

                    b.HasIndex("Symbol", "Date")
                        .IsUnique();

                    b.ToTable("TickerHistories");
                });

            modelBuilder.Entity("ScreenEdge.Entity.Entities.StockFundamental", b =>
                {
                    b.HasOne("ScreenEdge.Entity.Entities.DistinctStock", "DistinctStock")
                        .WithOne("Fundamental")
                        .HasForeignKey("ScreenEdge.Entity.Entities.StockFundamental", "DistinctStockId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DistinctStock");
                });

            modelBuilder.Entity("ScreenEdge.Entity.Entities.DistinctStock", b =>
                {
                    b.Navigation("Fundamental");
                });
#pragma warning restore 612, 618
        }
    }
}
